#!/usr/bin/env bash
# =============================================================================
# generate-manifest.sh - Generate files.txt manifest for remote installation
# =============================================================================
# Usage: ./generate-manifest.sh
#
# Generates a list of all files in .tihonspec/ that need to be downloaded
# for remote installation.
# =============================================================================

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
OUTPUT_FILE="$SCRIPT_DIR/files.txt"

# Get current timestamp
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date +%Y-%m-%dT%H:%M:%SZ)

# Generate manifest header
cat > "$OUTPUT_FILE" <<EOF
# TihonSpec File Manifest
# Generated: $TIMESTAMP
# This file is auto-generated by generate-manifest.sh
# Do not edit manually

EOF

# Find all files in .tihonspec/ and append to manifest
# Exclude: hidden files (except .tihonspec.env.example), .git, __pycache__, *.pyc
find "$SCRIPT_DIR/.tihonspec" -type f \
  ! -name ".*" \
  ! -path "*/.git/*" \
  ! -path "*/__pycache__/*" \
  ! -name "*.pyc" \
  | sed "s|$SCRIPT_DIR/||" \
  | sort >> "$OUTPUT_FILE"

# Also include specific dotfiles that are needed
if [[ -f "$SCRIPT_DIR/.tihonspec/.tihonspec.env.example" ]]; then
  echo ".tihonspec/.tihonspec.env.example" >> "$OUTPUT_FILE"
fi

# Count files
FILE_COUNT=$(grep -v '^#' "$OUTPUT_FILE" | grep -v '^$' | wc -l | tr -d ' ')

echo "Generated $OUTPUT_FILE with $FILE_COUNT files"
